---
- hosts: lbServer
  sudo: yes
  tasks:
    - name: install haproxy
      yum: name=haproxy state=present
    - name: ensure haproxy is running
      service:
        name: haproxy 
        state: started
    - name: Update HAProxy config
      template: src=../templates/haproxy.cfg
        dest=/etc/haproxy/haproxy.cfg
        backup=yes
    - name: restart haproxy
      service:
        name: haproxy 
        state: restarted
    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Restart the firewalld service to load in the firewall changes
      service: 
        name: firewalld 
        state: restarted
  vars:
    haproxy_backend_servers:
      - {name: webserverA, ip: 192.168.56.117, port: 80, paramstring: cookie A check}
      - {name: webserverB, ip: 192.168.56.118, port: 80, paramstring: cookie B check}