---
- hosts: webserverA, webserverB
  sudo: yes
  tasks:
    - name: install epel-release
      yum: 
        name: epel-release
    - name: install nodejs
      yum: 
        name: nodejs
    - name: Install the globally package "express".
      npm:
        name: express
        global: yes
        state: present
    - name: Creates directory
      file:
        path: /var/www
        state: directory
    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Create server.js file
      template: src=../templates/server.js
        dest=/var/www/server.js
        backup=yes
    - name: Create index.html file
      template: src=../templates/index.html
        dest=/var/www/index.html
        backup=yes
    - name: Copy server service
      template: src=../templates/serverApp.service
        dest=/etc/systemd/system/serverApp.service
    - name: restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
      systemd:
        state: restarted
        daemon_reload: yes
        name: serverApp
    - name: Enable service serverApp
      service:
        name: serverApp
        state: started
        enabled: yes
    - name: Restart the firewalld service to load in the firewall changes
      service: 
        name: firewalld 
        state: restarted
